apiVersion: v1
kind: Service
metadata:
  name: bank-transaction-system-service
  namespace: default  # 指定命名空间
spec:
  selector:
    app: bank-transaction-system-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8088
  type: LoadBalancer